### ISSUE TITLE
Unable to test app config variables during development

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#220]
It seems like config variables are not available for testing during development. The are only shown for apps imported from RAS. See video recording:
http://youtu.be/Vuix4_A_Ba4

**Comment by otsakir** [comment]
@ivelin, the problem here is that the application is exported as a **raw** rvd project package and then imported as a RAS package. Raw packages can be imported only from RVD itself. See screenshot:

The labels the help tips and the error messages need improvement for sure though. This is not the first time a user gets confused with two different export formats.

![import_raw_projects](https://cloud.githubusercontent.com/assets/8972800/7223807/fe2b7e7c-e730-11e4-860d-59c2fa963eb3.png)

**Comment by scottbarstow** [comment]
This worked for me.  Had additional issues but they don't belong with this particular problem.

**Comment by otsakir** [comment]
Ok @scottbarstow. 

@ivelin, i'm closing this issue unless someone has something to note.
