### ISSUE TITLE
Cannot place a call with a Docker setup

### ISSUE THREAD

**Issue by BabyOnMove** [Mobicents/RestComm#290]
Hi Dear, 

I have done the download of the Boot2Docker and then I ran the following command to get restcomm
docker run -e VOICERSS_KEY="2xxxxxxxxxxxxxxxxxadfcd984e21688f1" --name=restcomm -d -p 8080:8080 -p 5080:5080 -p 5082:5082 -p 5080:5080/udp -p 65000-65535:65000-65535/udp gvagenas/restcomm:7.3.0

Then the command "docker start restcomm" is OK and I get back restcomm

Following the guide I then connect to my local IP to get the Olympus application working, I log in. Then I try as required a call to the +1234 

But the call never work and I get back the following message into the logs:
2015-06-11 23:12:34 Call to +1234 has failed with "Problem to setup services".

Can you tell me what I did wrong somewhere? 
I would like to get the possibility to make some call simulation

Thanks in advance for any support

**Comment by gvagenas** [comment]
Hi,

Seems that media server is not running and that's why the call is falling.

From what you described,  you first executed the "docker run...."  command
and the "docker start restcomm" which is not correct since Restcomm is
started after docker run.

You should "docker stop restcomm", then "docker rm restcomm" and start
fresh using the "docker run ..." command.

Also, please make sure you are running the latest docker 1.6.

George
