### ISSUE TITLE
RVD new module selection doesn't work as expected

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#310]
I am trying to edit my app on my live restcomm instance and when I go to RVD, the drop down menu for selecting a module does not do what I expect. 

The blue label showing the current module has an arrow next to it. When I click on the arrow, I see a list of modules. Selecting a module has no effect.

The white tab label of the module itself also has an arrow next to it. Selecting that arrow blanks out the module panel.

Eventually I found out that the arrow next to the Search icon is the one that actually changes modules as expected.

Usability wise it can be improved. It took me trying all module lables with arrows next to them to see which one does the work.

![screen shot 2015-06-23 at 1 04 59 am](https://cloud.githubusercontent.com/assets/2234901/8299890/2186592e-1944-11e5-8290-1f8409cfbfe9.png)

![screen shot 2015-06-23 at 1 07 01 am](https://cloud.githubusercontent.com/assets/2234901/8299911/91a087e8-1944-11e5-96ed-5abfd807907f.png)

![screen shot 2015-06-23 at 1 06 55 am](https://cloud.githubusercontent.com/assets/2234901/8299913/96e9400a-1944-11e5-94b4-0044b73f800e.png)

**Comment by ivelin** [comment]
Upon further investigation I feel like a DODO bird.

The blue label drop down arrow selects the startup module.
The white tab drop down arrow "minimizes" / hides the given module.

I am not sure what can be improved UX wise. Maybe a question for community vote?

Ivelin

**Comment by otsakir** [comment]
There have been a lot of complains against current module UI and generally it takes a while to find how to open an existing module. 

Taking into account user comments i'm aware of my suggestion is this:

 - A dropdown list of existing modules should be present on the far left, at the position where the "Startup module - *" button currently is. That's the most common thing to do. A special "View all" entry list can also be used.
 - The module filtering feature (the text box above "Search for modules") does not seem to be used. It's primary purpose is to affect the content of the dropdown list of modules so that one can find a module by name or apply  a filter using a regex e.g. 'admin*'. We can just hide it and have a small "filter" button to make it appear.
 - The "Start module - *" button is not a common operation. It can be moved to the far right at the place where "Search for modules" is.
 - "+ New module" is just fine.

**Comment by ivelin** [comment]
I think these observations are legit, although I haven't used RVD enough to confirm the frequency.

Is there a tracking library in place to help us track user interactions with the app?
http://luisfarzati.github.io/angulartics/  ?

**Comment by scottbarstow** [comment]
In addition to the problem you identified, Ivelin, it is also true that when you log in to the console and select an app, you don't see all of the module tabs.  I only see the Welcome module, and have to go over to the Search in upper right, click the Drop down and select my other module in order to get it to appear.

This resets after every login, meaning that I have to do this EVERY time I log in in order to access the other modules.  If this is not related, then I can open a new bug.  Let me know @ivelin or @otsakir

**Comment by otsakir** [comment]
@scottbarstow , i think you are referring to #213 .

@ivelin , there is no tracking library currently. I agree it's a good idea to add one. I've created a new issue for this - #312

**Comment by scottbarstow** [comment]
You are correct

On Wed, Jun 24, 2015 at 1:59 AM, Orestis Tsakiridis <
notifications@github.com> wrote:

> @scottbarstow <https://github.com/scottbarstow> , i think you are
> referring to #213 <https://github.com/Mobicents/RestComm/issues/213> .
>
> @ivelin <https://github.com/ivelin> , there is no tracking library
> currently. I agree it's a good idea to add one. I've created a new issue
> for this - #312 <https://github.com/Mobicents/RestComm/issues/312>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/310#issuecomment-114738479>.
>



-- 
scottbarstow.com
@scottbarstow
