### ISSUE TITLE
Email Tag implementation for the RVD application.

### ISSUE THREAD

**Issue by leftyb** [Mobicents/RestComm#339]
Add a new Email Step for the RVD.

**Comment by otsakir** [comment]
Great work Lefteris!

Just reviewed your #340 PR  and everything works perfect. Both in terms of functionality and code style.

I noticed you 've also added a handler method for email submission and a 'Redirect To'.

One comment only:

'From' and 'To' fields in emailStep.html use email syntax validation. So variable reference values like '$sender' will fail parsing and consequently the project won't be able to run.

The reason is that variable expansion does not work in the client at design time. The workaround is to use looser validation on the client. It's not optimal but can work until a smarter validation scheme that takes into account variable syntax is implemented.

Moving forward i think loosening client validation for 'From' and 'To' and adding 'Email' element to USSD projects will complete the picture. You think you can take care of that?

I can then add lookup variables and do the merge.

wdyt?

**Comment by leftyb** [comment]
Hi Oresti,

Thank you for the review.
Perfect i will do a PR, as we commented.

Lefteris.
