### ISSUE TITLE
Restcomm uses internal Amazon ip in the contact header during invite

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/RestComm#353]
Scenario: Olympus calls Messenger (through restcomm). INVITE from Restcomm -> Messenger uses in the contact the internal Amazon ip instead of the external. Is that correct behaviour? As a result, when messenger hangs up, it tries to reach Restcomm at the internal Amazon ip and fails.

Here's the capture (collected at the messenger side to see the attempts to reach Restcomm at the internal Amazon IP):

https://gist.github.com/atsakiridis/6d0ec02ef753db599a26

Same scenario using Linphone -> Jitsi works, but it seems that Jitsi although receiving the INVITE with the 'internal' contact from Restcomm, still sends the BYE to the external IP.

**Comment by gvagenas** [comment]
Since this is a client to client call, Restcomm bypass proxy and load balancer using:
                ((SipSessionExt) outRequest.getSession()).setBypassLoadBalancer(true);
                ((SipSessionExt) outRequest.getSession()).setBypassProxy(true);
and thus SipServlet container creates the contact header using the ip address of the sip connector.

The Contact header is a system header and cannot be modified by the application and we need to check with @deruelle for how to fix this issue.

@atsakiridis a workaround would be path the Request URI of the BYE message in the same way Restcomm tries to do it:
1. Create BYE
2. Check the ip address of Request URI.
   2.1 If the ip address is public, proceed 
   2.2. If the ip address is any local ip address, then change it to the remote address (the address where the initial INVITE came from) gov.nist.javax.sip.message.SIPMessage.getRemoteAddress()

George

**Comment by deruelle** [comment]
Why do we bypass the Load Balancer ? we shouldn't I think as when we will support replication, any subsequent requests from the client we reach will not be failed over to another node if the former node failed.
See https://github.com/Mobicents/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1646

Setting ((SipSessionExt) outRequest.getSession()).setBypassLoadBalancer(false); will make it work

**Comment by gvagenas** [comment]
The reason we bypass LB for client-to-client calls is NAT.

When a Restcomm client register to Restcomm the client's router will keep open the NATed port but will associated it with the ip address of Restcomm.

If LB was on the picture, Restcomm would ask LB to reach client Alice and so the INVITE would be send out from the LB  public ip address. This INVITE would never reach Alice client because the router of client, keeps open the NATed port only for traffic from the Restcomm ip address.

There was a discussion with Jean about this issue back then, on an email thread with subject "Restcomm + LB: Calling Restcomm clients" which I will forward to the team again.

George

**Comment by atsakiridis** [comment]
This is fixed on the iOS SDK side, with https://github.com/Mobicents/restcomm-ios-sdk/issues/192
