### ISSUE TITLE
RVD Fails to login when RestComm is on HTTPS

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#484]
when I try to login with HTTPS it fails, when I try to login via HTTP it works

https://192.168.0.44/restcomm-rvd/services/auth/login 500 (Internal Server Error)b @ angular-1.2.4.min.js:72C @ angular-1.2.4.min.js:68c.$get.h @ angular-1.2.4.min.js:66k.promise.then.C @ angular-1.2.4.min.js:92k.promise.then.C @ angular-1.2.4.min.js:92(anonymous function) @ angular-1.2.4.min.js:93a.$get.h.$eval @ angular-1.2.4.min.js:101a.$get.h.$digest @ angular-1.2.4.min.js:99a.$get.h.$apply @ angular-1.2.4.min.js:102(anonymous function) @ angular-1.2.4.min.js:178n.event.dispatch @ jquery-1.11.0.min.js:3n.event.add.r.handle @ jquery-1.11.0.min.js:3

services.js:72 error logging in

I noticed there is some hard coded http:// in services.js

**Comment by deruelle** [comment]
Fixing http:// hard coded url in services.js doesn't help it seems the issue is in the java classes to login

**Comment by deruelle** [comment]
Confirmed, it looks like https://github.com/Mobicents/RestComm/blob/master/restcomm/restcomm.rvd/src/main/java/org/mobicents/servlet/restcomm/rvd/security/AuthenticationService.java#L34 uses hard coded http:// as well, we need to be able to make that relative so people can login with http:// or https://

**Comment by otsakir** [comment]
@deruelle , there is an interesting situation here. 

RVD has been using Restcomm's IP not domain name in order to proxy authentication requests. For SSL, IP won't work as the certificate is issued for a domain and not an IP. I decided to use the domain from the request (HttpServletRequest.getServerName()) to tackle the issue and it worked.

However, i'm not sure if this has any implications in a production environment with NAT involved etc. Since now, RVD was relying on the request.getLocalAddr(). In an AMI environment that would return internal IP i think. Will RVD be able to access restcomm  from inside by using 'ServerName' instead of IP?

Also, i needed to explicitly add the self-signed cert i used for testing to my JVM trust store. Otherwise SSL negotiation fails. Shall we consider disabling SSL checks here? 

Btw, I think we should at some point consider the interface between Restcomm and RVD. It's a very common task when developing RVD to try to reach Restcomm and each time having to overcome the same issues of determining the address, establishing trust etc. Things should be easier. Maybe we should open a discussion on that.

**Comment by otsakir** [comment]
Further comment and commits on #485 .

**Comment by otsakir** [comment]
The issue has been fixed when a valid certificate is used (see #485). A related issue is #525 which has been fixed too.
