### ISSUE TITLE
Amazon RDS Issue with CAST

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#493]
https://gist.github.com/deruelle/095413c1d23a718d040f

**Comment by croufay** [comment]
@deruelle ,

This might be due to the space between the CAST and the ()


CAST (${usageExpr} AS SIGNED) AS "usage",

Should be

CAST(${usageExpr} AS SIGNED) AS "usage",


https://github.com/Mobicents/RestComm/blob/master/restcomm/restcomm.application/src/main/webapp/WEB-INF/scripts/mariadb/sql/usage.xml#L14



Regards

**Comment by deruelle** [comment]
that did the trick indeed.I committed the changes in branch Issue-493

**Comment by deruelle** [comment]
Merged in https://github.com/Mobicents/RestComm/pull/510
