### ISSUE TITLE
SMPP RestComm SIP Port is hardcoded in the SMPP Bind

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#495]
See https://github.com/Mobicents/RestComm/blob/87e52fc39fa10d83a3096dfce1f143e1c7b238ed/restcomm/restcomm.smpp/src/main/java/org/mobicents/servlet/restcomm/smpp/SmppClientOpsThread.java#L456

**Comment by deruelle** [comment]
It's Working. But I still have an NPE, see https://gist.github.com/deruelle/094479f94c3bc8a7022d.
It's not related to this issue though I guess

**Comment by gvagenas** [comment]
@deruelle the reason for the NPE is that Call actor at https://github.com/Mobicents/RestComm/blob/charles_smpp/restcomm/restcomm.telephony/src/main/java/org/mobicents/servlet/restcomm/telephony/CallManager.java#L1056 is null.
This is wrong, the 202 Accepted response shouldn't be routed to the CallManager since this is a response for an SMS session and we have to change that.

Can you please elaborate on the call flow. From the logs I can see the following:

1. Nexmo sends SMS to Restcomm, destination 33644630186
2. Restcomm sends SMS to Nexmo, destination 33644630186
3. Restcomm sends 202 response to Nexmo
4. Nexmo sends 202 response to Restcomm

Why the message goes back and forth to Nexmo and Restcomm ?

**Comment by deruelle** [comment]
Nexmo send SMS to RestComm via SMPP here. So I think that's RestComm messing up. I think Restcomm when it receives an SMPP message converts it to SIP and send it to RestComm via itself.

**Comment by gvagenas** [comment]
Oh right, this is one of my comments to change in the review I did for the SMPP branch. When the SMPP service of Restcomm will receive new SIP message over the SMPP connection it will convert it to SIP message and send it to Restcomm again. We need to change this.

**Comment by deruelle** [comment]
in the meanwhile, can we fix this NPE @croufay we should actually probably notify the SMPP to do a delivery report that the message was correctly delivered

**Comment by croufay** [comment]
@deruelle 
Do you have the output of the NPE.?
