### ISSUE TITLE
Test Record feature on Dialogic XMS

### ISSUE THREAD

**Issue by hrosa** [Mobicents/RestComm#658]
Test Record feature on Dialogic XMS

**Comment by hrosa** [comment]
@RomanDS Can you expose the recording files (accessible via HTTP, for example) on XMS instance so we can test their quality?

**Comment by RomanDS** [comment]
Hi Henrique,
Need to triple check and see if http record is an option. Otherwise there is a way to do NFS mount and place files on a different server that way. You can also create NFS mount on a different server to XMS where the RestComm records the files and that should work as well. Let me take a look tomorrow and Ill get back to you.

Regards,
Roman
